// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IERC20} from "./interfaces/IERC20.sol";
import {IERC3009} from "./interfaces/IERC3009.sol";
import {IMelodyPaySettlement} from "./interfaces/IMelodyPaySettlement.sol";
import {ReentrancyGuard} from "./common/ReentrancyGuard.sol";
import {Pausable} from "./common/Pausable.sol";
import {Ownable2Step} from "./common/Ownable2Step.sol";
import {SafeERC20} from "./common/SafeERC20.sol";

/**
 * @title MelodyPaySettlement
 * @notice Multi-chain acoustic payment settlement contract using EIP-3009.
 * @dev Designed for Arc Network (Genesis USDC: 0x3600000000000000000000000000000000000000)
 *      and other EVM networks (Base, Arbitrum, Monad, Ethereum).
 *      Supports both receiveWithAuthorization and transferWithAuthorization settlement flows.
 */
contract MelodyPaySettlement is IMelodyPaySettlement, ReentrancyGuard, Pausable, Ownable2Step {
    using SafeERC20 for IERC20;

    // Default Arc Genesis canonical USDC address (ERC-20 interface, 6 decimals)
    address public constant ARC_GENESIS_USDC = 0x3600000000000000000000000000000000000000;

    // Canonical USDC Token & EIP-3009 Interfaces
    IERC20 public immutable usdcToken;
    IERC3009 public immutable usdcAuthorization;

    // Default Project Treasury
    address public override defaultTreasury;

    // Anti-replay registry: authorizer => nonce => settled
    mapping(address => mapping(bytes32 => bool)) public override isSettled;

    // Order lookup: orderId => nonce
    mapping(bytes32 => bytes32) public override orderToSettlement;

    /**
     * @notice Initializes the settlement contract.
     * @param _usdcAddress The USDC contract address (pass ARC_GENESIS_USDC or address(0) for Arc Network).
     * @param _initialTreasury The default project treasury wallet.
     */
    constructor(address _usdcAddress, address _initialTreasury) Ownable2Step(msg.sender) {
        if (_usdcAddress == address(0)) {
            _usdcAddress = ARC_GENESIS_USDC;
        }
        if (_initialTreasury == address(0)) revert ZeroAddress();

        usdcToken = IERC20(_usdcAddress);
        usdcAuthorization = IERC3009(_usdcAddress);
        defaultTreasury = _initialTreasury;

        emit DefaultTreasuryUpdated(address(0), _initialTreasury);
    }

    /**
     * @notice Settles an acoustic sound payment authorized via EIP-3009 receiveWithAuthorization.
     * @dev Payer signs typed data with `to = address(this)`. Funds are received by contract and forwarded to `to`.
     * @param from The payer/authorizer wallet address.
     * @param to The recipient wallet (defaults to `defaultTreasury` if address(0)).
     * @param value The token amount to transfer in 6-decimal base units (e.g. 1 USDC = 1_000_000).
     * @param validAfter Earliest unix timestamp when the authorization is valid.
     * @param validBefore Expiry unix timestamp for the authorization (60s acoustic TTL).
     * @param nonce Unique 32-byte random nonce generated by hardware TRNG.
     * @param orderId Optional merchant POS order identifier for deduplication (pass bytes32(0) if unused).
     * @param v ECDSA recovery byte.
     * @param r ECDSA signature output r.
     * @param s ECDSA signature output s.
     * @return True if settlement succeeds.
     */
    function settlePayment(
        address from,
        address to,
        uint256 value,
        uint256 validAfter,
        uint256 validBefore,
        bytes32 nonce,
        bytes32 orderId,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external override nonReentrant whenNotPaused returns (bool) {
        if (to == address(0)) {
            to = defaultTreasury;
        }
        _validateSettlement(from, to, value, validAfter, validBefore, nonce, orderId);

        // Lock replay mapping before external interactions (Checks-Effects-Interactions pattern)
        isSettled[from][nonce] = true;
        if (orderId != bytes32(0)) {
            orderToSettlement[orderId] = nonce;
        }

        emit SoundPaymentSettled(from, to, value, nonce, orderId, block.timestamp);

        // Pull USDC from authorizer to this settlement contract via EIP-3009
        usdcAuthorization.receiveWithAuthorization(
            from,
            address(this),
            value,
            validAfter,
            validBefore,
            nonce,
            v,
            r,
            s
        );

        // Immediately forward USDC to designated recipient (merchant or treasury)
        usdcToken.safeTransfer(to, value);

        return true;
    }

    /**
     * @notice Settles an acoustic sound payment authorized via EIP-3009 transferWithAuthorization.
     * @dev Payer signs typed data with `to = recipient` directly. Settlement contract submits the authorization.
     * @param from The payer/authorizer wallet address.
     * @param to The recipient wallet (merchant address).
     * @param value The token amount to transfer in 6-decimal base units.
     * @param validAfter Earliest unix timestamp when the authorization is valid.
     * @param validBefore Expiry unix timestamp for the authorization.
     * @param nonce Unique 32-byte random nonce.
     * @param orderId Optional merchant POS order identifier.
     * @param v ECDSA recovery byte.
     * @param r ECDSA signature output r.
     * @param s ECDSA signature output s.
     * @return True if settlement succeeds.
     */
    function settleWithTransferAuthorization(
        address from,
        address to,
        uint256 value,
        uint256 validAfter,
        uint256 validBefore,
        bytes32 nonce,
        bytes32 orderId,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external override nonReentrant whenNotPaused returns (bool) {
        if (to == address(0)) {
            to = defaultTreasury;
        }
        _validateSettlement(from, to, value, validAfter, validBefore, nonce, orderId);

        isSettled[from][nonce] = true;
        if (orderId != bytes32(0)) {
            orderToSettlement[orderId] = nonce;
        }

        emit SoundPaymentSettled(from, to, value, nonce, orderId, block.timestamp);

        // Direct transfer from payer to merchant using transferWithAuthorization
        usdcAuthorization.transferWithAuthorization(
            from,
            to,
            value,
            validAfter,
            validBefore,
            nonce,
            v,
            r,
            s
        );

        return true;
    }

    /**
     * @notice Updates the default treasury address.
     * @param newTreasury New project treasury address.
     */
    function setDefaultTreasury(address newTreasury) external onlyOwner {
        if (newTreasury == address(0)) revert ZeroAddress();
        address oldTreasury = defaultTreasury;
        defaultTreasury = newTreasury;
        emit DefaultTreasuryUpdated(oldTreasury, newTreasury);
    }

    /**
     * @notice Pauses the settlement contract in case of emergency.
     */
    function pause() external onlyOwner {
        _pause();
    }

    /**
     * @notice Unpauses the settlement contract.
     */
    function unpause() external onlyOwner {
        _unpause();
    }

    // --- Internal Helpers ---

    function _validateSettlement(
        address from,
        address to,
        uint256 value,
        uint256 validAfter,
        uint256 validBefore,
        bytes32 nonce,
        bytes32 orderId
    ) internal view {
        if (from == address(0) || to == address(0)) revert ZeroAddress();
        if (value == 0) revert ZeroAmount();
        if (block.timestamp > validBefore) revert AuthorizationExpired(validBefore, block.timestamp);
        if (block.timestamp < validAfter) revert AuthorizationNotYetValid(validAfter, block.timestamp);
        if (isSettled[from][nonce]) revert ReplayAttackDetected(from, nonce);
        if (orderId != bytes32(0) && orderToSettlement[orderId] != bytes32(0)) {
            revert OrderAlreadySettled(orderId);
        }
    }
}
